
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

image:
  file: .devcontainer/Dockerfile
  context: ./.devcontainer
checkoutLocation: "gitpod-experiment"
workspaceLocation: "gitpod-experiment"
tasks:
  - init: |
      docker-compose up -d
    
    command: |
      docker exec splunk splunk status
    
vscode:
  extensions:
    - redhat.ansible