
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

image:
  file: .devcontainer/gitpod.Dockerfile
  context: ./.devcontainer
checkoutLocation: "gitpod-experiment"
workspaceLocation: "gitpod-experiment"
tasks:
  - init: |
      ansible-galaxy role install -r ansible/roles/requirements.yml
    
    command: |
      ansible-playbook -c localhost ansible/playbooks/setup.yml -e username=gitpod
    
vscode:
  extensions:
    - redhat.ansible
    - ms-azuretools.vscode-docker
    - mhutchie.git-graph
    - eamodio.gitlens
    - ms-azure-devops.azure-pipelines