
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

image:
  file: .devcontainer/gitpod.Dockerfile
  context: ./.devcontainer
checkoutLocation: "gitpod-experiment"
workspaceLocation: "gitpod-experiment"
tasks:
  - before: |
      ansible-galaxy role install -r ./.devcontainer/ansible/roles/requirements.yml
      ansible-playbook -c localhost ./.devcontainer/ansible/playbooks/setup.yml -e username=gitpod

    init: |
      echo "Welcome to the preconfigured development environment! ✌️"

vscode:
  extensions:
    - redhat.ansible
    - ms-azuretools.vscode-docker
    - mhutchie.git-graph
    - eamodio.gitlens
